parameters:
    app.version: !php/const App\VersionApplication::VERSION
    env(GITHUB_TOKEN): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Logging\SensitiveDataProcessor:
        tags:
            - { name: monolog.processor }

    asset_mapper.importmap.auditor:
        class: Symfony\Component\AssetMapper\ImportMap\ImportMapAuditor
        arguments:
            $configReader: '@asset_mapper.importmap.config_reader'
            $httpClient: '@github_advisories.client'
