framework:
    secret: '%env(APP_SECRET)%'
    trusted_hosts:
        - '%env(TRUSTED_HOST_PATTERN)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - 'x-forwarded-for'
        - 'x-forwarded-host'
        - 'x-forwarded-proto'
        - 'x-forwarded-port'
    http_client:
        scoped_clients:
            github_advisories.client:
                base_uri: 'https://api.github.com'
                auth_bearer: '%env(GITHUB_TOKEN)%'
                headers:
                    Accept: 'application/vnd.github+json'
                    X-GitHub-Api-Version: '2022-11-28'
    router:
        utf8: true
    csrf_protection: true
    http_method_override: false
    session:
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax

when@prod:
    framework:
        session:
            cookie_secure: true
            cookie_httponly: true
            cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
