framework:
    secret: '%env(APP_SECRET)%'
    trusted_hosts:
        - '%env(TRUSTED_HOST_PATTERN)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - 'x-forwarded-for'
        - 'x-forwarded-host'
        - 'x-forwarded-proto'
        - 'x-forwarded-port'
    router:
        utf8: true
    csrf_protection: true
    http_method_override: false
    session:
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax

when@prod:
    framework:
        session:
            cookie_secure: true
            cookie_httponly: true
            cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
